server:
  port: 8080
  address: localhost
  tomcat:
    threads:
      max: 512
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: springboot-board
  datasource:
    driver-class: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board_24?serverTimezone=Asia/Seoul
    username: song
    password: dho7410

mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true